In [1]:
import numpy as np

In [3]:
npmatrix1 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]])
print(npmatrix1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [4]:
randomlyInitializedArray = np.random.randint(1,20,(4,5))
print(randomlyInitializedArray)

[[ 6  3 10 12 18]
 [ 6 16 16 19 13]
 [11 15 16 16 18]
 [11  2 15 13  2]]


In [5]:
print(npmatrix1.T)

[[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]


In [6]:
squarematrix = np.array([[1,1,1],[2,2,2],[3,3,3]])
print(squarematrix)

[[1 1 1]
 [2 2 2]
 [3 3 3]]


In [7]:
# calculating the determinant of matrix
det = np.linalg.det(squarematrix)
  
print("\nDeterminant of given 3x3 matrix:")
print(int(det))


Determinant of given 3x3 matrix:
0


In [8]:
randomlyInitializedMatrix = np.random.randint(1,30,(5,4))
print(randomlyInitializedMatrix)

[[ 6 18  2  2]
 [23  9 25 17]
 [ 4  7  4 13]
 [23  5 10  5]
 [25  1 29 25]]


In [10]:
matrix2 = np.array([[1,2],[3,4]])
matrix1 = np.array([[1,1],[1,1]])
print(matrix1)
print(matrix2)

[[1 1]
 [1 1]]
[[1 2]
 [3 4]]


In [12]:
res = np.dot(matrix1,matrix2)
print(res)

[[4 6]
 [4 6]]


In [13]:
result = matrix1 * matrix2
print(result)

[[1 2]
 [3 4]]


In [15]:
mean = np.mean(matrix2)
print("mean:",mean)

mean: 2.5


In [16]:
median = np.median(matrix2)
print("median",median)

median 2.5


In [17]:
npmatrix1[:,1]

array([ 2,  6, 10, 14, 18])

In [25]:
import pandas as pd
iris = pd.read_csv("C:\\Users\Lenovo\Documents\Iris.csv")
print(iris.mean())

Id               75.500000
SepalLengthCm     5.843333
SepalWidthCm      3.054000
PetalLengthCm     3.758667
PetalWidthCm      1.198667
dtype: float64


In [27]:
print("Shape:",npmatrix1.shape)
a = np.arange(10) 
print("Arrange:",a)
print("Flags:\n",npmatrix1.flags)
print("Length of each elements in bytes:",npmatrix1.itemsize)

Shape: (5, 4)
Arrange: [0 1 2 3 4 5 6 7 8 9]
Flags:
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

Length of each elements in bytes: 4
