**Exercise 1:**

Try logistic regression on BuyComputer dataset and set Random state=Your_RollNumber (last 3 digit of ID, incase if you don’t have ID)

implementation of logistic regression function

In [ ]:
import numpy as np
import pandas as pd
import io
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score

In [ ]:
data = pd.read_csv('BuyComputer.csv')
data.drop(columns=['User ID',],axis=1,inplace=True)
data.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
label=data.iloc[:,-1].values
x=data.iloc[:,:-1].values

print('label : \n',label)
print('\nx : \n',x)

label : 
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]

x : 
 [[    19  19000]
 [    35  20000]
 [    26  43000]
 [    27  57000]
 [    19  76000]
 [    27  58000]
 [    27  84000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,label,test_size=0.4,random_state=61)

sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

y_pred  = []
len_x=len(x_train[0])
w = []
b=0.2
print(len_x)

entries = len(x_train[:,0])
print(entries)
for weights in range(len_x):
    w.append(0)
print(w)

2
240
[0, 0]


In [ ]:
def sigmoid(z):
    final = 1/(1+np.exp(-z))
    return final

In [ ]:
def loss_func(y,a):
    aT=a.T
    j= (-1/entries) * (np.sum((aT*np.log(y)) + ((1-aT) * (np.log(1-y)))))
    return j

In [ ]:
def predict(inputs,m):
    print(m)
    y_pred=np.zeros(m);
    for i in range(m):
        if inputs[i] > 0.5:
            y_pred[i] = 1
    return y_pred

In [ ]:
dw = []
db = 0
J = 0
alpha = 0.1
for x in range(len_x):
    dw.append(0)

In [ ]:
for i in range(3000):
    y=sigmoid((np.dot(w,x_train.T)+b));
    cost = loss_func(y,y_train);
    dw = (1/entries) * (np.dot(x_train.T,(y-y_train.T).T));
    db=(1/entries) * (np.sum(y-y_train.T))
    w=w-(alpha * dw.T)
    b=b-(alpha * db)

print("\nWeight : ",w)
print("\nBias : " ,b)

train_pred=sigmoid(np.dot(w,x_train.T)+b)

test_pred=sigmoid(np.dot(w,x_test.T)+b)

y_pred=predict(train_pred,x_train.shape[0])
print('pridiction of x_train: \n',y_pred)

x_pred_test=predict(test_pred,x_test.shape[0])
print('pridiction of x_test: \n',x_pred_test)


Weight :  [2.35625942 1.04217951]

Bias :  -0.9112948033494777
240
pridiction of x_train: 
 [1. 1. 1. 1. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 0.
 0. 1. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0.
 1. 1. 1. 0. 0. 0. 1. 0. 0. 1. 0. 1. 0. 0. 1. 1. 1. 0. 0. 1. 0. 0. 1. 0.
 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0.
 1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 1. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 1. 0. 1.
 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0.
 1. 0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 1. 1. 0. 1. 0. 1. 0. 1. 0. 0. 0. 1. 0.
 1. 0. 0. 1. 1. 0. 0. 0. 1. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 1. 0. 0. 0. 1.
 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
160
pridiction of x_test: 
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 1. 1. 0. 1. 0. 1. 1. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 0.
 0

In [ ]:
print("actal value\n" ,y_test,y_test.shape)

print("\naccuracy score : ",accuracy_score(x_pred_test,y_test))

actal value
 [0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 1 0 1 1 1 0
 1 1 1 1 0 0 0 1 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 0 1 1 1 1 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 0 1 0
 0 0 0 1 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1
 0 1 0 1 0 1 0 0 0 1 0 0] (160,)

accuracy score :  0.86875


# using Defualt Logistic Regressionation function

In [ ]:
from sklearn.linear_model import LogisticRegression
lrmodel= LogisticRegression(random_state = 40)

lrmodel.fit(x_train,y_train)

pred=lrmodel.predict(x_test)

print("\naccuracy score : ",accuracy_score(pred,y_test))


accuracy score :  0.86875


# Exercise 2

In [1]:
from __future__ import absolute_import, division, print_function
import tensorflow as tf
import numpy as np
from tensorflow.keras.datasets import mnist

In [2]:
#step 2
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = np.array(x_train, np.float32), np.array(x_test, np.float32)


num_features=784
x_train, x_test = x_train.reshape([-1, num_features]), x_test.reshape([-1, num_features])
print(x_train.shape)
x_train, x_test = x_train / 255., x_test / 255.
print(x_train)

11501568/11490434 [==============================] - 0s 0us/step
(60000, 784)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [3]:
#Step 3
num_classes = 10 # 0 to 9 digits
num_features = 784 # 28*28
learning_rate = 0.01
training_steps = 1000
batch_size = 256
display_step = 50

In [4]:
#step 4
train_data=tf.data.Dataset.from_tensor_slices((x_train,y_train))
train_data=train_data.repeat().shuffle(5000).batch(batch_size).prefetch(1)
print(train_data)

<PrefetchDataset element_spec=(TensorSpec(shape=(None, 784), dtype=tf.float32, name=None), TensorSpec(shape=(None,), dtype=tf.uint8, name=None))>


In [5]:
#step 5
W = tf.Variable(tf.ones([num_features, num_classes]), name="weight")
print(W)
b = tf.Variable(tf.zeros([num_classes]), name="bias")
print(b)

<tf.Variable 'weight:0' shape=(784, 10) dtype=float32, numpy=
array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)>
<tf.Variable 'bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>


In [6]:
#step 6
def logistic_regression(x):
    return tf.nn.softmax(tf.matmul(x, W) + b)

def cross_entropy(y_pred, y_true):
    y_true = tf.one_hot(y_true, depth=num_classes)
    y_pred = tf.clip_by_value(y_pred, 1e-9, 1.)
    return tf.reduce_mean(-tf.reduce_sum(y_true * tf.math.log(y_pred)))

In [7]:
#step 7
def accuracy(y_pred, y_true):
    correct_prediction = tf.equal(tf.argmax(y_pred, 1), tf.cast(y_true, tf.int64))
    return tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [8]:
#step 8
optimizer = tf.optimizers.SGD(learning_rate)
def run_optimization(x, y):
    with tf.GradientTape() as g:
        pred = logistic_regression(x)
        loss = cross_entropy(pred, y)
    gradients = g.gradient(loss, [W, b])
    optimizer.apply_gradients(zip(gradients, [W, b]))

In [9]:
#step 9
for step, (batch_x, batch_y) in enumerate(train_data.take(training_steps), 1):
    run_optimization(batch_x, batch_y)
    if step % display_step == 0:
        prediction = logistic_regression(batch_x)
        loss = cross_entropy(prediction, batch_y)
        accurracy = accuracy(prediction, batch_y)
        print("step: %i, loss: %f, accuracy: %f" % (step, loss, accurracy))

step: 50, loss: 630.911621, accuracy: 0.832031
step: 100, loss: 600.645386, accuracy: 0.816406
step: 150, loss: 575.896667, accuracy: 0.832031
step: 200, loss: 432.009369, accuracy: 0.871094
step: 250, loss: 406.723328, accuracy: 0.839844
step: 300, loss: 620.143005, accuracy: 0.851562
step: 350, loss: 526.843201, accuracy: 0.847656
step: 400, loss: 499.287781, accuracy: 0.835938
step: 450, loss: 645.335449, accuracy: 0.855469
step: 500, loss: 867.895447, accuracy: 0.753906
step: 550, loss: 514.719482, accuracy: 0.855469
step: 600, loss: 610.844604, accuracy: 0.804688
step: 650, loss: 596.118530, accuracy: 0.851562
step: 700, loss: 547.238708, accuracy: 0.843750
step: 750, loss: 445.066895, accuracy: 0.886719
step: 800, loss: 353.229828, accuracy: 0.886719
step: 850, loss: 804.940002, accuracy: 0.789062
step: 900, loss: 593.608887, accuracy: 0.843750
step: 950, loss: 623.948853, accuracy: 0.843750
step: 1000, loss: 824.046326, accuracy: 0.820312


In [10]:
#step 10
prediction = logistic_regression(x_test)

print("Test Accuracy: %f" % accuracy(prediction, y_test))

Test Accuracy: 0.836600
