**AIM : Implement Linear Regression Algorithm on the given dataset.**
**Exercise 1: Try Linear Regression just using numpy (Without Tensorflow/Pytorch or other torch library). You can optionally use sklearn.**

In [1]:
import numpy as np
import torch

In [2]:
#Input (Temp, Rainfall, Humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

#Target (Apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

#Converting inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [3]:
#Weights and Biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights : \n", w)
print("\nBiases : \n", b)

Weights : 
 tensor([[-1.9858,  0.1541,  0.2423]], requires_grad=True)

Biases : 
 tensor([-1.5206], requires_grad=True)


In [4]:
#Defining the model
def model(x):
    return  torch.mm(x, w.t(), out=None) + b

In [5]:
#Generating Predictions
preds = model(inputs)

#Comparing Predictions with targets
print("Predictions : \n", preds)
print("\nTargets : \n", targets)

Predictions : 
 tensor([[-125.7425],
        [-153.1629],
        [-139.5860],
        [-188.4832],
        [-106.7882]], grad_fn=<AddBackward0>)

Targets : 
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [6]:
#Defining MSE loss function
def MSELoss(P, T): 
  sum = 0
  n = len(T)
  for j in range(0, n):
    sum += (T[j] - P[j]) * (T[j] - P[j])
  return sum / n

loss = MSELoss(preds, targets)
print("MSE Loss : ", loss[0])

MSE Loss :  tensor(48608.7109, grad_fn=<SelectBackward0>)


In [7]:
#Computing Gradient
loss.backward()
print("Gradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)

Gradients for weights : 
 tensor([[-37207.0703, -38649.6172, -24108.9551]])

Gradient for biases: 
 tensor([-437.9051])


In [8]:
#Adjusting weights and biases using Gradient Descent
#Reseting gradients
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()

print("Gradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)

print("\nNew Weights : \n", w)
print("\nNew Biases : \n", b)

Gradients for weights : 
 tensor([[0., 0., 0.]])

Gradient for biases: 
 tensor([0.])

New Weights : 
 tensor([[-1.6138,  0.5406,  0.4834]], requires_grad=True)

New Biases : 
 tensor([-1.5162], requires_grad=True)


In [9]:
#Calculating  new loss
preds = model(inputs)

loss = MSELoss(preds, targets)
print("New MSE Loss : ", loss[0])

New MSE Loss :  tensor(20207.3164, grad_fn=<SelectBackward0>)


In [10]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MSELoss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss[0])

MSE Loss :  tensor(27.7097, grad_fn=<SelectBackward0>)


**Exercise 2: Try Linear regression on same prediction data using Tensorflow**

In [11]:
import torch.nn as nn

In [12]:
#Input (Temp, Rainfall, Humidity)
inputs = np.array([[73, 67, 43],
                  [91, 88, 64],
                  [87, 134, 58],
                  [102, 43, 37],
                  [69, 96, 70]], dtype='float32')

#Target (Apples)
targets = np.array([[56],
                    [81],
                    [119],
                    [22],
                    [103]], dtype='float32')

#Converting inputs and targets to tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [13]:
#Weights and Biases
w = torch.randn(1, 3, requires_grad=True)
b = torch.randn(1, requires_grad=True)

print("Weights : \n", w)
print("\nBiases : \n", b)

Weights : 
 tensor([[-1.3378,  1.2460, -0.1562]], requires_grad=True)

Biases : 
 tensor([-0.3494], requires_grad=True)


In [14]:
#Defining the model
def model(x):
    return  x @ w.t() + b

In [15]:
#Generating Predictions
preds = model(inputs)

#Comparing Predictions with targets
print("Predictions : \n", preds)
print("\nTargets : \n", targets)

Predictions : 
 tensor([[-21.2446],
        [-22.4399],
        [ 41.1634],
        [-89.0064],
        [ 16.0218]], grad_fn=<AddBackward0>)

Targets : 
 tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])


In [16]:
MSELoss = nn.MSELoss()
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss)

MSE Loss :  tensor(8522.5400, grad_fn=<MseLossBackward0>)


In [17]:
#Computing Gradient
loss.backward()
print("\nGradients for weights : \n", w.grad)
print("\nGradient for biases: \n", b.grad)


Gradients for weights : 
 tensor([[-15659.1270, -15132.5537,  -9860.7617]])

Gradient for biases: 
 tensor([-182.6023])


In [18]:
# Train for 100 epochs
for i in range(100):
    preds = model(inputs)
    loss = MSELoss(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

preds = model(inputs)
loss = MSELoss(preds, targets)
print("MSE Loss : ", loss)

MSE Loss :  tensor(72.1748, grad_fn=<MseLossBackward0>)
